### ISSUE TITLE
Remove `dplyr` dependency

### ISSUE THREAD

**Issue by DavisVaughan** [jyuu/butcher#1]
This might have been a temporary thing on your part, but dplyr is a large dependency, and we probably won't actually _need_ it for anything. Generally I'd include dplyr as a package dep if i was extending it or wanted `group_by()`.

If you really need `bind_rows()` (I see you use it), I'd recommend switching it out for `vctrs` and `vec_rbind()`. You'll need the development version, so you'll need to set vctrs to be a `Remote` in the DESCRIPTION file. Just ask me if you want to do this and I can show you what I mean by that

**Comment by jyuu** [comment]
Done! Dependencies to dplyr and magrittr removed
