### ISSUE TITLE
`sysdata.rda` thoughts

### ISSUE THREAD

**Issue by DavisVaughan** [jyuu/butcher#3]
I'm not entirely sure what the right approach should be here, but I _think_ that rather than having 1 sysdata.rda file, I would rather take the readxl approach where the data files are all stored in `inst/extdata/` and then a helper is provided to load the examples.

https://github.com/tidyverse/readxl/blob/master/R/example.R
https://github.com/tidyverse/readxl/tree/master/inst/extdata

The `inst/extdata/` directory is blessed by CRAN
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Data-in-packages

As it currently stands, the issues with the sysdata.rda approach are:

- It is hard to tell at a glance exactly what example data sets are there
- These are actually all _internal only_. So you can't use them in examples. For example, this won't actually work `axe_misc(glmnet_multi)` (I'm fairly certain). However, I'm not sure you'd actually want to use them in examples. Rather, you might want to actually show examples of creating the objects with the modeling functions, and then pruning them. This gives a clearer picture of how the package will be used.

I _do_ really like the fact that there is a script that generates the test data files.

So here are my thoughts:

- Create an `inst/extdata/` folder. This will be included in the R package.
- Create a `inst/extdata-scripts/` folder. This won't be bundled with the R package, so use `usethis::use_build_ignore("inst/extdata-scripts")` to add it do the `.Rbuildignore`. (I think that should work)
- I would have 1 file per data set in `extdata-scripts/` that generates 1 dataset in `extdata/`. They should have matching file names. 
- Create a helper like readxl that can read in the datasets when requested.
- Use this helper in tests, but maybe not in examples. In examples, as mentioned above i think it would be most clear if we could actually `library()` the relevant package and show off the methods after using the package to create a model object.
- I am unsure if the helper should be exported at the current moment.

I'm going to open another issue about what I think the examples sections could look like.

**Comment by jyuu** [comment]
Refactoring addressed, all examples moved from `R/sysdata.rda` into its own respective files under `inst/extdata`. Lingering questions: 

- If the model object is specified, the helper displays the script used to create the object.. How should the helper be expanded? Should the helper be exported? 
- How large is okay for`.rda` files stored here?
- What if the `.rda` file (i.e., stan output) includes components of a S4 class?

**Comment by DavisVaughan** [comment]
> If the model object is specified, the helper displays the script used to create the object

Today we discussed that the helper should probably just return the data directly, rather than printing a script and loading the data

> Should the helper be exported?

I don't think so

> How large is okay for `.rda` files stored here?

I would try and keep them as small as you can. There's a _general_ limit of about 5mb in an R package, but that isn't a hard limit. I would shoot for closeish to that and we can discuss other solutions if needed

>  components of a S4 class

Since S4 comes with base R, I think this will be okay and won't break anything
