### ISSUE TITLE
Model specific help files

### ISSUE THREAD

**Issue by DavisVaughan** [jyuu/butcher#4]
I think it might be useful to have the help files be "model specific" as well.

So, what I am suggesting is that `lm` would have one help file that would have `axe_env.lm`, `axe_call.lm` and so on all documented in one place.

That would allow you to document exactly what `axe_misc.lm` does, right in the lm specific help doc.

Doing this is a bit of a trick, because you have to really know how roxygen comments work. It looks something like this:

```r
#' Axing an lm
#'
#' This is where all of the lm specific documentation lies
#'
#'
#' @name axe-lm
NULL

#' @rdname axe-lm
#' @export
axe_call.lm <- function(x, ...) {
  x$call <- call("dummy_call")
  x
}

#' @rdname axe-lm
#' @export
axe_env.lm <- function(x, ...) {
  # Environment in terms
  x$terms <- axe_env(x$terms, ...)
  # Environment in model
  attributes(x$model)$terms <- axe_env(attributes(x$model)$terms, ...)
  x
}
```

<img width="944" alt="Screen Shot 2019-06-17 at 9 12 24 AM" src="https://user-images.githubusercontent.com/19150088/59606803-0ad02d00-90e0-11e9-99e1-9afeedc26975.png">

This is also where I would actually use `lm()` to create a lm object, and then you could call all of the relevant axing functions on it to show what it does.

This is slightly more complicated when a package is required to call the model (`lm()` comes with base R). Like for flexsurv, to be able to run `library(flexsurv)` in the examples section, you have to have flexsurv as a Suggests. I am still not sure if this is what we will do in the long run, but we can give it a try for now.

**Comment by jyuu** [comment]
Done. Lingering questions: 

- Should we include all the packages used to create this model objects under Suggests?

**Comment by DavisVaughan** [comment]
> Should we include all the packages used to create this model objects under Suggests?

For now, yes! That way you can call `library(<pkg>)` in your examples and (if you need to) test files and `devtools::check()` will not complain
