### ISSUE TITLE
prototype butchered object console messages

### ISSUE THREAD

**Issue by jyuu** [jyuu/butcher#42]
Emojis?

**Comment by jyuu** [comment]
I prototyped console msgs the user might want to see after executing an axe generic on a fitted model object. It is only applied it to `lm` objects at the moment, and will be replicated among others once the means by which it is implemented is efficient enough.  

``` r
library(butcher)
library(dplyr)

# Create lm
in_house_model <- function() {
  some_junk_in_the_environment <- matrix(1:1e6, ncol = 10) # we didn't know about
  lm(mpg ~ ., data = mtcars) 
}
lm_fit <- in_house_model()
# Execute the axe_env method on this lm object 
out <- axe_env(lm_fit)
# Execute the axe_call method
out <- axe_call(lm_fit)
# Now if using pipes 
out <- lm_fit %>% 
  axe_env() %>% 
  axe_call()
# And execute all possible axe methods via `butcher`
out <- butcher(lm_fit) 
```

The current butcher function:

```{r} 
butcher <- function(x, ...) {
  old <- x
  pre <- options(usethis.quiet = TRUE)
  x <- axe_call(x, ...)
  x <- axe_ctrl(x, ...)
  x <- axe_data(x, ...)
  x <- axe_env(x, ...)
  x <- axe_fitted(x, ...)
  pre <- options(usethis.quiet = FALSE)
  assess_object(old, x, working = c("predict"))
  x
}
```

Questions: 
1) Not sure how best to leverage the `usethis.quiet` flag so there isn't a flood of console messages, as one would see when piping a bunch of `axe_` methods
2) Is there way to capture the console output, so it can be aggregated and printed coherently when the user runs `butcher`? (i.e., add all memory released, set union all active/ inactive functions)? 
3) Ideas around revamping the console output in general? Or how it is implemented?


<sup>Created on 2019-07-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by topepo** [comment]
It's more traditional to have a `verbose` option. You_could_ try this a few different ways:

```r
chatty_butcher <- function(x, verbose = FALSE, ...) {
  old <- x
  x <- axe_call(x, verbose = verbose, ...)
  x <- axe_ctrl(x, verbose = verbose, ...)
  x <- axe_data(x, verbose = verbose, ...)
  x <- axe_env(x, verbose = verbose, ...)
  x <- axe_fitted(x, verbose = verbose, ...)
  assess_object(old, x, working = c("predict"))
  x
}
```

```r
sunken_butcher <- function(x, verbose = FALSE, ...) {
  old <- x
  
  temp_file <- tempfile()
  sink(file = temp_file)
  x <- axe_call(x, verbose = TRUE, ...)
  x <- axe_ctrl(x, verbose = TRUE, ...)
  x <- axe_data(x, verbose = TRUE, ...)
  x <- axe_env(x, verbose = TRUE, ...)
  x <- axe_fitted(x, verbose = TRUE, ...)
  sink()
  
  if (verbose) {
    cat(temp_file, sep = "n")
  }
  
  assess_object(old, x, working = c("predict"))
  x
}
```

Although ti seems like we are repeating ourselves with `chatty_butcher()`, I feel like `sunken_butcher()` is inelegant. 

In either case, I would almost never make a function that prints output without the ability to turn it off (and usually default `verbose = FALSE`). 

For what to print... this is pretty subjective. I like:

```
> # Execute the axe_call method
> out <- axe_call(lm_fit)
✔ Memory released: 10 MB
✖ Disabled: `print()`
```

@DavisVaughan would probably have some ideas too.
