### ISSUE TITLE
Don't export methods specific to a model if they just call the default method

### ISSUE THREAD

**Issue by DavisVaughan** [jyuu/butcher#5]
I know I said otherwise in the meeting last week, but I now think that if a model doesn't have an applicable `axe_env` method, then it should just use `axe_env.default` directly rather than having a `axe_env.model` method that calls the default.

The reason for this is related to #4. If you only export methods that are actually relevant to the model, then they are the only things that will show up in the model specific help files.

Meaning you don't want `axe_misc.lm` to show up in the lm specific help doc if it doesn't actually do anything.

**Comment by jyuu** [comment]
Removed all function placeholders, in most models, if no action is taken, it now defaults to method.default
