### ISSUE TITLE
butcher class assignment

### ISSUE THREAD

**Issue by jyuu** [jyuu/butcher#50]
Class assignment (addition) only happens when the user calls the `butcher` function. What if only the sub axe functions are used? How to elegantly add class assignment without `if` statements? Is there a way to do so globally to any kind of axing done on an object?

**Comment by DavisVaughan** [comment]
I _think_ you can modify `x` in the generic, before the dispatch happens. So you could do something like this:

`intersect(<new_class>, class(x))`


right before `UseMethod()` here
https://github.com/jyuu/butcher/blob/6f0bea6377d7c981eb7b8060b2a9a9cdcf22e83f/R/axe-generics.R#L63

Where `<new_class>` could be generated from the existing class? `paste0("butchered_", class(x)[1])`

That would mean you only modify the class 1 time per generic, not in every single method.

**Comment by DavisVaughan** [comment]
I would extract out a helper function for this so you can do `x <- butcher_class(x)` all in one line
