### ISSUE TITLE
name conflicts

### ISSUE THREAD

**Issue by jyuu** [jyuu/butcher#51]
does butcher-package export conflict with export of `butcher` function?

**Comment by DavisVaughan** [comment]
I think you can remove this line
https://github.com/jyuu/butcher/blob/6f0bea6377d7c981eb7b8060b2a9a9cdcf22e83f/R/butcher-package.R#L2

that would avoid any conflict

see vctrs, which doesn't have that line
https://github.com/r-lib/vctrs/blob/master/R/vctrs-package.R
