### ISSUE TITLE
test_that block structure

### ISSUE THREAD

**Issue by DavisVaughan** [jyuu/butcher#7]
Generally, I would encourage using small `test_that` blocks for each model + `axe_*` function combination.

So it would be more like `test_that("lm + axe_env() works", ...)`. This way it is self documenting (you don't have to do `# LM`), and when you run the tests and anything fails it tells you exactly which model failed.

You'll invert the test files so it will be `test-lm.R`, but the same principle will apply!

**Comment by jyuu** [comment]
Done, ongoing tests will be carried out in this format
